### ISSUE TITLE
Ruby 3.2 unsupported 

### ISSUE THREAD

**Issue by aheumaier** [standardrb/vscode-standard-ruby#4]
On setting the standardrb path to ruby@3.2 results in 
```[client] No Gemfile found in the current workspace
[client] Disabling because the extension does not support this version of the standard gem.
[client]   Version reported by `/opt/homebrew/opt/ruby@3.2/bin/ruby -v`: ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22] (>= 1.24.3 required)
[client] Restarting language server...
[client] Disabling because the extension does not support this version of the standard gem.
[client]   Version reported by `/opt/homebrew/opt/ruby@3.2/bin/ruby -v`: ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22] (>= 1.24.3 required)
```

**Comment by gfguthrie** [comment]
It's saying you need to upgrade your version of the `standard` gem.

**Comment by searls** [comment]
Yes, the issue here seems to be that you may have `standardRuby.commandPath` set to something that's resulting in the extension seeing your `standardrb` command as `/opt/homebrew/opt/ruby@3.2/bin/ruby`, so it's passing the version check before launching. Can you send your JSON config for every key starting with `standardRuby.`?
